### ISSUE TITLE
🚗 Roadmap for first beta RC

### ISSUE THREAD

**Issue by jgaehring** [jgaehring/harvest-calendar-react#9]
## Main Features
- [x] Sort crops alphabetically #2 
- [x] Export calendar as SVG #3
- [x] Delete crops #13

## Bug fixes, maintenance & minor enhancements
- [x] Fix controlled input warning #1
- [x] Refactoring #6 
- [x] Basic aesthetics #8 
- [x] Add credits and link to home page #16 
- [ ] Alert user if they try to extend season beyond end/start of the year #5  

## Deployment
- [x] Setup Netlify deployment
- [x] Update README and add some screenshots
- [x] Add to portfolio and promote (https://github.com/jgaehring/jgaehring.com/issues/2)

**Comment by jgaehring** [comment]
might just want to let this be superceded by https://github.com/jgaehring/harvest-calendar-react/milestone/1

**Comment by jgaehring** [comment]
most of the deployment options seem to be very well summarized here:
https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#deployment

**Comment by jgaehring** [comment]
I think I'm going to punt on issue #5 for now, but will leave it open until I finish adding this to my portfolio.

As for my portfolio, I think I can close this issue once I finish the project preview on the Home page.

**Comment by jgaehring** [comment]
Resolved by jgaehring/jgaehring.com@9744b5f.

The main thing holding this up now is just completing the other portfolio items for jgaehring/jgaehring.com#2, so this issue can be closed.
